### ISSUE TITLE
AWS CodePipelineServiceRole を CFn で生成する

### ISSUE THREAD

**Issue by y-web21** [y-web21/port_lara_media#27]
# 目的

環境構築の自動化

# やること

AIM Role を作成して

```yml
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
         ...
      Path: /
      Policies:
         ...
```

パイプライン側の `# RoleArn`部分に反映できるようにする

```yml
  myCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      # 現状は Arn Strings
      RoleArn: !Ref CodePipelineRoleAr
      # 生成した Role を参照する
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
```
