### ISSUE TITLE
プロジェクト用のデプロイアーティファクトS3バケットをCFnで用意する

### ISSUE THREAD

**Issue by y-web21** [y-web21/port_lara_media#28]
# 目的

デプロイ環境構築の自動化

# やること

- GitHubから取得したデプロイアーティファクトのS3バケットをCFnで自動生成する。
- CLI スタックデリートコマンドでS3バケットが消せずにスタックが削除できない問題を解決する。

`DeletionPolicy: Retain`を加えて

また、cliでS3バケットを削除する方法を検討する。

```yml
  # S3Bucket
  # ArtifactBucket:
  #   Type: AWS::S3::Bucket
        DeletionPolicy: Retain
  #   Properties:
  #     BucketName: !Sub 'codepipeline-${AWS::Region}-${AWS::AccountId}'

  myCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "CodePipeline-${ApplicationName}"
      ArtifactStore:
        Type: S3
        Location: !Ref CodeDeployS3ArtifactBucket
        # Location: !Ref ArtifactBucket
      RoleArn: !Ref CodePipelineRoleArn
      # RoleArn: !Ref CodePipelineServiceRole
```
